# Form implementation generated from reading ui file 'aNewAltman.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 186)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #121212;\n"
"color:#fff;\n"
"font:11pt \"Helvetica\";\n"
"}\n"
"\n"
"QLabel {\n"
"background:transparent;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"                                 QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgba(22,22,22,100);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(32, 32, 32);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"\n"
"/*\n"
"VERTICAL\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:vertical {\n"
"    border-radius: 11px;\n"
"    width: 22px;\n"
"    margin: 0px;\n"
"    background-color: rgba(33,33,33,100);\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgba(44,44,44,100);    \n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 22px;\n"
"    width: 22px;\n"
"    margin: 0px;\n"
"    border-radius: 11px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////////////////////////////\n"
"                                    QScrollBar\n"
"//////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background:transparent;\n"
"    height: 12px;\n"
"    margin: 0px 10px 0px 10px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(22,22,22);\n"
"    min-width:24px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, \n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:transparent;\n"
"    width: 12px;\n"
"    margin: 10px 0px 10px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(22,22,22);\n"
"    min-height: 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"background-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainpanePage1 = QtWidgets.QWidget()
        self.mainpanePage1.setObjectName("mainpanePage1")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.mainpanePage1)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.mainpanePage1)
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"margin-left:9px;\n"
"padding-top:2px;\n"
"padding-bottom:2px;\n"
"background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"font-weight:bold;\n"
"font-size:8pt;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-radius: 4px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.tab)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_15.setMinimumSize(QtCore.QSize(0, 110))
        self.label_15.setStyleSheet("")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout_14.addWidget(self.label_15, 0, 1, 1, 1)
        self.altmans_sleep = QtWidgets.QSlider(parent=self.frame_4)
        self.altmans_sleep.setMinimumSize(QtCore.QSize(45, 0))
        self.altmans_sleep.setMaximumSize(QtCore.QSize(16777215, 110))
        self.altmans_sleep.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(87,111,215);}\n"
"QSlider::handle:vertical:hover {background:rgb(127,151,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(37,61,165);}\n"
"QSlider::groove:vertical:hover {background:rgba(87,111,215,0.25);}\n"
"QSlider::groove:vertical {background:rgba(87,111,215,0.15);}\n"
"\n"
"        ")
        self.altmans_sleep.setMaximum(5)
        self.altmans_sleep.setTracking(True)
        self.altmans_sleep.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_sleep.setInvertedAppearance(True)
        self.altmans_sleep.setObjectName("altmans_sleep")
        self.gridLayout_14.addWidget(self.altmans_sleep, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/basicsblue.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_11 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_21.setMinimumSize(QtCore.QSize(0, 110))
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_20.addWidget(self.label_21, 0, 1, 1, 1)
        self.altmans_speech = QtWidgets.QSlider(parent=self.frame_11)
        self.altmans_speech.setMinimumSize(QtCore.QSize(45, 0))
        self.altmans_speech.setMaximumSize(QtCore.QSize(16777215, 110))
        self.altmans_speech.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(68,212,146);}\n"
"QSlider::handle:vertical:hover {background:rgb(108,252,186);}\n"
"QSlider::handle:vertical:pressed {background:rgb(18,162,96);}\n"
"QSlider::groove:vertical:hover {background:rgba(68,212,146,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(68,212,146,0.15);}\n"
"\n"
"        ")
        self.altmans_speech.setMaximum(5)
        self.altmans_speech.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_speech.setInvertedAppearance(True)
        self.altmans_speech.setObjectName("altmans_speech")
        self.gridLayout_20.addWidget(self.altmans_speech, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_11, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/asdfasdfasfsadfasf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(parent=self.tab_4)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_16.setMinimumSize(QtCore.QSize(0, 110))
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 0, 1, 1, 1)
        self.altmans_activity = QtWidgets.QSlider(parent=self.frame_5)
        self.altmans_activity.setMinimumSize(QtCore.QSize(45, 0))
        self.altmans_activity.setMaximumSize(QtCore.QSize(16777215, 110))
        self.altmans_activity.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(245,235,103);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,255,143);}\n"
"QSlider::handle:vertical:pressed {background:rgb(195,185,53);}\n"
"QSlider::groove:vertical:hover {background:rgba(245,235,103,0.25);}\n"
"QSlider::groove:vertical {background:rgba(245,235,103,0.15);}\n"
"        ")
        self.altmans_activity.setMaximum(5)
        self.altmans_activity.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_activity.setInvertedAppearance(True)
        self.altmans_activity.setObjectName("altmans_activity")
        self.gridLayout_15.addWidget(self.altmans_activity, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/effort.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_4, icon2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_12 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_22.setMinimumSize(QtCore.QSize(0, 110))
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_21.addWidget(self.label_22, 0, 1, 1, 1)
        self.altmans_cheer = QtWidgets.QSlider(parent=self.frame_12)
        self.altmans_cheer.setMinimumSize(QtCore.QSize(45, 0))
        self.altmans_cheer.setMaximumSize(QtCore.QSize(16777215, 110))
        self.altmans_cheer.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(255,161,92);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,201,132);}\n"
"QSlider::handle:vertical:pressed {background:rgb(205,111,42);}\n"
"QSlider::groove:vertical:hover {background:rgba(255,161,92,0.25);}\n"
"QSlider::groove:vertical {background:rgba(255,161,92,0.15);}\n"
"\n"
"        ")
        self.altmans_cheer.setMaximum(5)
        self.altmans_cheer.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_cheer.setInvertedAppearance(True)
        self.altmans_cheer.setObjectName("altmans_cheer")
        self.gridLayout_21.addWidget(self.altmans_cheer, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_12, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/asdfasfasfasfas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_3, icon3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_7.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_13 = QtWidgets.QFrame(parent=self.tab_6)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_23 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_23.setMinimumSize(QtCore.QSize(0, 110))
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_22.addWidget(self.label_23, 0, 1, 1, 1)
        self.altmans_confidence = QtWidgets.QSlider(parent=self.frame_13)
        self.altmans_confidence.setMinimumSize(QtCore.QSize(45, 0))
        self.altmans_confidence.setMaximumSize(QtCore.QSize(16777215, 110))
        self.altmans_confidence.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(199,76,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.25);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.15);}\n"
"\n"
"        ")
        self.altmans_confidence.setMaximum(5)
        self.altmans_confidence.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_confidence.setInvertedAppearance(True)
        self.altmans_confidence.setObjectName("altmans_confidence")
        self.gridLayout_22.addWidget(self.altmans_confidence, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_13, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/asdfasfas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/outlookHole.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_6, icon4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_9.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.tab_5)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(12)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.altmans_summary_label = QtWidgets.QLabel(parent=self.frame)
        self.altmans_summary_label.setStyleSheet("font-weight:bold;margin-top:4px; margin-bottom:4px;")
        self.altmans_summary_label.setObjectName("altmans_summary_label")
        self.gridLayout_5.addWidget(self.altmans_summary_label, 1, 1, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame1 = QtWidgets.QFrame(parent=self.frame)
        self.frame1.setObjectName("frame1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame1)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 282, 112))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame1, 2, 1, 1, 2)
        self.altmans_summary = QtWidgets.QSlider(parent=self.frame)
        self.altmans_summary.setMinimumSize(QtCore.QSize(45, 110))
        self.altmans_summary.setMaximumSize(QtCore.QSize(16777215, 110))
        self.altmans_summary.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(244,56,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.25);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.35);}\n"
"\n"
"        ")
        self.altmans_summary.setMaximum(25)
        self.altmans_summary.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_summary.setInvertedAppearance(True)
        self.altmans_summary.setObjectName("altmans_summary")
        self.gridLayout_5.addWidget(self.altmans_summary, 0, 0, 3, 1)
        self.gridLayout_9.addWidget(self.frame, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_24.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.mainpanePage1)
        self.mainpanePage2 = QtWidgets.QWidget()
        self.mainpanePage2.setObjectName("mainpanePage2")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.mainpanePage2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.altmans_manic_rating_table = QtWidgets.QTableView(parent=self.mainpanePage2)
        self.altmans_manic_rating_table.setStyleSheet("\n"
"QTableView {\n"
"background-color: transparent;\n"
"selection-background-color: #7e57c2;\n"
"gridline-color:transparent;\n"
"color: rgb(77, 15, 26);\n"
"}\n"
"QTableView::item {\n"
"padding: 1px;color: rgb(77, 15, 26);\n"
"background:rgb(229,100,111);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: rgb(255, 255, 255);\n"
"background:rgb(23, 23, 23);\n"
"}\n"
"    ")
        self.altmans_manic_rating_table.setShowGrid(False)
        self.altmans_manic_rating_table.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.altmans_manic_rating_table.setSortingEnabled(True)
        self.altmans_manic_rating_table.setObjectName("altmans_manic_rating_table")
        self.altmans_manic_rating_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_25.addWidget(self.altmans_manic_rating_table, 1, 0, 1, 1)
        self.hidemeframe = QtWidgets.QFrame(parent=self.mainpanePage2)
        self.hidemeframe.setObjectName("hidemeframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.hidemeframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.altman_time = QtWidgets.QTimeEdit(parent=self.hidemeframe)
        self.altman_time.setObjectName("altman_time")
        self.horizontalLayout.addWidget(self.altman_time)
        self.altman_date = QtWidgets.QDateEdit(parent=self.hidemeframe)
        self.altman_date.setObjectName("altman_date")
        self.horizontalLayout.addWidget(self.altman_date)
        self.gridLayout_25.addWidget(self.hidemeframe, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.mainpanePage2)
        self.gridLayout_12.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 16))
        self.menubar.setObjectName("menubar")
        self.menuBECK = QtWidgets.QMenu(parent=self.menubar)
        self.menuBECK.setObjectName("menuBECK")
        self.menuViews = QtWidgets.QMenu(parent=self.menubar)
        self.menuViews.setObjectName("menuViews")
        MainWindow.setMenuBar(self.menubar)
        self.actionCommit = QtGui.QAction(parent=MainWindow)
        self.actionCommit.setObjectName("actionCommit")
        self.actionDelete_Record = QtGui.QAction(parent=MainWindow)
        self.actionDelete_Record.setObjectName("actionDelete_Record")
        self.actionMinimize = QtGui.QAction(parent=MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionMaximize = QtGui.QAction(parent=MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionInput_View = QtGui.QAction(parent=MainWindow)
        self.actionInput_View.setObjectName("actionInput_View")
        self.actionDataview = QtGui.QAction(parent=MainWindow)
        self.actionDataview.setObjectName("actionDataview")
        self.menuBECK.addAction(self.actionCommit)
        self.menuBECK.addAction(self.actionDelete_Record)
        self.menuBECK.addAction(self.actionMinimize)
        self.menuBECK.addAction(self.actionMaximize)
        self.menuViews.addAction(self.actionInput_View)
        self.menuViews.addAction(self.actionDataview)
        self.menubar.addAction(self.menuBECK.menuAction())
        self.menubar.addAction(self.menuViews.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.altmans_summary.valueChanged['int'].connect(self.altmans_summary_label.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Usual 7-8 hours, needed.</p><p><span style=\" font-size:10pt;\">I needed less sleep than usual and still functioned well.</span></p><p>6 hours or less slept feels like 8</p><p>Debating pulling an all nighter.</p><p>Well, fuck it. I am up still. </p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>I speak normal, for me.</p><p><span style=\" font-size:10pt;\">Stumbling over words due to having too many at once.</span></p><p>Getting annoying, talking over others, quicker speech.</p><p>Talking more, talking faster, making sense still</p><p><span style=\" font-size:10pt;\">Salad of word.</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Today, I\'m not so horny.</span></p><p><span style=\" font-size:10pt;\">Today, I\'m quite horny.</span></p><p>Today, some could say I\'m edging towards deviance pun intended.</p><p>I am starting to collect mp4s</p><p>I will regret my morrow.</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Base</span></p><p>Feeling a little better than objectively should.</p><p>More confident than I objectively deserve. </p><p><span style=\" font-size:10pt;\">I\'m so cool so hot so sex.</span></p><p>I\'m GOD but not God God cause that\'s God. </p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Base</span></p><p>Willing to dip my toes into it.</p><p>Getting cocky.</p><p>Becoming arrogant.</p><p>Please god shut me up.</p></body></html>"))
        self.altmans_summary_label.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">How Manic Are You?</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">• A cutoff score of 6 </span>or higher indicates a high probability of a manic or hypomanic condition (based on a sensitivity rating of 85.5% and a specificity rating of 87.3%).</p><p><span style=\" font-weight:600;\">• A score of 6 </span>or higher may indicate a need for treatment and/or further diagnostic workup to confirm a diagnosis of mania or hypomania.</p><p><span style=\" font-weight:600;\">• A score of 5</span> or lower is less likely to be associated with significant symptoms of mania.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Sum"))
        self.altman_time.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.altman_date.setDisplayFormat(_translate("MainWindow", "yyyy/mm/dd"))
        self.menuBECK.setTitle(_translate("MainWindow", "Altman"))
        self.menuViews.setTitle(_translate("MainWindow", "Views"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionCommit.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionDelete_Record.setText(_translate("MainWindow", "Delete Record"))
        self.actionDelete_Record.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionMinimize.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionMaximize.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionInput_View.setText(_translate("MainWindow", "Input View"))
        self.actionInput_View.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionDataview.setText(_translate("MainWindow", "Dataview"))
        self.actionDataview.setShortcut(_translate("MainWindow", "Ctrl+2"))
